export const states = [
    { text: 'Acre', value: 'Acre', key: 'acre' },
    { text: 'Alagoas', value: 'Alagoas', key: 'alagoas' },
    { text: 'Amapá', value: 'Amapá', key: 'amapa' },
    { text: 'Amazonas', value: 'Amazonas', key: 'amazonas' },
    { text: 'Bahia', value: 'Amazonas', key: 'bahia' },
    { text: 'Ceará', value: 'Ceará', key: 'ceara' },
    { text: 'Distrito Federal', value: 'Distrito Federal', key: 'distrito_federal' },
    { text: 'Espírito Santo', value: 'Espírito Santo', key: 'espirito_santo' },
    { text: 'Goiás', value: 'Goiás', key: 'goias' },
    { text: 'Mato Grosso', value: 'Mato Grosso', key: 'mato_grosso' },
    { text: 'Mato Grosso do Sul', value: 'Mato Grosso do Sul', key: 'mato_grosso_do_sul' },
    { text: 'Minas Gerais', value: 'Minas Gerais', key: 'Minas Gerais' },
    { text: 'Pará', value: 'Pará', key: 'para' },
    { text: 'Paraíba', value: 'Paraíba', key: 'paraiba' },
    { text: 'Paraná', value: 'Paraná', key: 'parana' },
    { text: 'Pernambuco', value: 'Pernambuco', key: 'pernambuco' },
    { text: 'Piauí', value: 'Piauí', key: 'piaui' },
    { text: 'Rio de Janeiro', value: 'Rio de Janeiro', key: 'rio_de_janeiro' },
    { text: 'Rio Grande do Norte', value: 'Rio Grande do Norte', key: 'rio_grande_do_norte' },
    { text: 'Rio Grande do Sul', value: 'Rio Grande do Sul', key: 'rio_grande_do_sul' },
    { text: 'Rondônia', value: 'Rondônia', key: 'rondonia' },
    { text: 'Roraima', value: 'Roraima', key: 'roraima' },
    { text: 'Santa Catarina', value: 'Santa Catarina', key: 'santa_catarina' },
    { text: 'São Paulo', value: 'São Paulo', key: 'sao_paulo' },
    { text: 'Sergipe', value: 'Sergipe', key: 'sergipe' },
    { text: 'Tocantins', value: 'Tocantins', key: 'tocantins' }
];